import {useEffect,useRef,useState} from 'react';
import L from 'leaflet';
import {jsonRequest,LatestRequest} from './api';
type RecordRow=Record<string,string>;
type Package={id:number;source_name:string;agency:RecordRow[];feed:RecordRow[];counts:Record<string,number>};
type Visit={visit:RecordRow;stop:RecordRow|null};
type Detail={package:Package;trip:RecordRow;shape:[number,number][];stops:Visit[];warning:string};
const period=(p:Package)=>p.feed.map(f=>`${f.feed_start_date} – ${f.feed_end_date} (version ${f.feed_version??'unspecified'})`).join('; ');
export function Plans(){
 const [packages,setPackages]=useState<Package[]>([]),[pid,setPid]=useState(''),[routes,setRoutes]=useState<RecordRow[]>([]),[route,setRoute]=useState(''),[trips,setTrips]=useState<RecordRow[]>([]),[trip,setTrip]=useState(''),[direction,setDirection]=useState(''),[detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[tileError,setTileError]=useState(false),[chosen,setChosen]=useState<Visit|null>(null),[showStops,setShowStops]=useState(true);
 const requests=useRef(new LatestRequest()),node=useRef<HTMLDivElement>(null),map=useRef<L.Map|null>(null),layer=useRef<L.LayerGroup|null>(null);
 async function fetchData<T>(url:string,accept:(v:T)=>void){setError('');setLoading(true);try{const v=await requests.current.run(s=>jsonRequest(url,s));if(v!==undefined){accept(v);setLoading(false);}}catch(e){setError((e as Error).message);setLoading(false);}}
 function refresh(){setPid('');setRoutes([]);setRoute('');setTrips([]);setTrip('');setDetail(null);setChosen(null);void fetchData<Package[]>('/api/plans/packages',setPackages);}
 useEffect(()=>{refresh();return()=>requests.current.cancel();},[]);
 useEffect(()=>{if(!node.current)return;const m=L.map(node.current,{preferCanvas:true}).setView([38.7,-9.15],10);map.current=m;layer.current=L.layerGroup().addTo(m);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).on('tileerror',()=>setTileError(true)).addTo(m);return()=>{m.remove();map.current=null;};},[]);
 useEffect(()=>{const group=layer.current;if(!group)return;group.clearLayers();if(!detail)return;
  if(detail.shape.length)L.polyline(detail.shape,{color:'#277a91',weight:4}).addTo(group);
  for(const v of detail.stops){if(!showStops||!v.stop?.stop_lat||!v.stop?.stop_lon)continue;const lat=Number(v.stop.stop_lat),lon=Number(v.stop.stop_lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))continue;const label=document.createElement('span');label.textContent=`${v.visit.stop_sequence}. ${v.stop.stop_name} (${v.visit.stop_id})`;L.circleMarker([lat,lon],{radius:5,color:'#173b48',fillColor:'#d1ed86',fillOpacity:1}).bindTooltip(label).on('click',()=>setChosen(v)).addTo(group);}
 },[detail,showStops]);
 useEffect(()=>{if(!detail||!map.current)return;const points:[number,number][]=detail.shape.length?detail.shape:detail.stops.filter(v=>v.stop?.stop_lat&&v.stop?.stop_lon).map(v=>[Number(v.stop!.stop_lat),Number(v.stop!.stop_lon)]);if(points.length)map.current.fitBounds(points,{padding:[45,45],maxZoom:15});},[detail]);
 const selectedPackage=packages.find(p=>String(p.id)===pid);
 const directions=[...new Set(trips.map(t=>t.direction_id??''))].sort();
 const candidates=trips.filter(t=>direction===''||t.direction_id===direction);
 return <div className="app"><aside><div className="brand"><span className="brandmark">h.</span> operation plans</div><h1>The planned network.</h1><div className="status">REFERENCE PLANS · NOT LIVE DATA</div><p className="muted">These supplied packages declare 2025 dates. They are not confirmed schedules for the 2026 vehicle replay. No vehicle positions or delay estimates are shown in this mode.</p>
 <button onClick={refresh}>Refresh plan packages</button>
 <label className="field">Operator / plan version<select aria-label="Plan package" value={pid} onChange={e=>{const value=e.target.value;setPid(value);setRoutes([]);setRoute('');setTrips([]);setTrip('');setDetail(null);setChosen(null);requests.current.cancel();setLoading(false);if(value)void fetchData<RecordRow[]>(`/api/plans/${value}/routes`,setRoutes);}}><option value="">Select an operator plan…</option>{packages.map(p=><option key={p.id} value={p.id}>{p.agency.map(a=>a.agency_name).join(', ')} · {p.source_name}</option>)}</select></label>
 {selectedPackage&&<><p className="muted">Declared validity (YYYYMMDD): {period(selectedPackage)}</p><label className="field">Line / route variant<select aria-label="Plan route" value={route} onChange={e=>{const value=e.target.value;setRoute(value);setTrips([]);setTrip('');setDirection('');setDetail(null);setChosen(null);requests.current.cancel();setLoading(false);if(value)void fetchData<RecordRow[]>(`/api/plans/${pid}/trips?${new URLSearchParams({route_id:value})}`,setTrips);}}><option value="">Select a route…</option>{routes.map(r=><option key={r.route_id} value={r.route_id}>{r.line_short_name||r.route_short_name||r.line_id} · {r.route_long_name||r.route_id} [{r.route_id}]</option>)}</select></label></>}
 {trips.length>0&&<><label className="field">Direction<select aria-label="Plan direction" value={direction} onChange={e=>{setDirection(e.target.value);setTrip('');setDetail(null);setChosen(null);requests.current.cancel();setLoading(false);}}><option value="">All directions</option>{directions.filter(Boolean).map(d=><option key={d}>{d}</option>)}</select></label><label className="field">Planned trip<select aria-label="Planned trip" value={trip} onChange={e=>{const value=e.target.value;setTrip(value);setDetail(null);setChosen(null);requests.current.cancel();setLoading(false);if(value)void fetchData<Detail>(`/api/plans/${pid}/trip?${new URLSearchParams({trip_id:value})}`,setDetail);}}><option value="">Select a planned trip…</option>{candidates.map(t=><option key={t.trip_id} value={t.trip_id}>{t.trip_headsign||'No headsign'} · {t.trip_id} · service {t.service_id}</option>)}</select></label><p className="muted">All services in this plan are listed; selecting a trip does not establish that it ran on any particular day. Direction codes are shown as supplied.</p></>}
 {loading&&<p role="status">Loading plan data…</p>}{error&&<div className="error" role="alert">{error}</div>}{!loading&&!error&&!packages.length&&<p>No plans imported yet. The plan importer may be waiting for the vehicle import to finish. See README for import commands.</p>}{route&&!loading&&!error&&!trips.length&&<p>No planned trips found for this route.</p>}
 {detail&&<><h2>Displayed planned trip</h2><p>{detail.trip.trip_headsign||detail.trip.trip_id}</p><label className="field"><span><input type="checkbox" checked={showStops} onChange={e=>setShowStops(e.target.checked)}/> Show stop locations</span></label><p className="muted">{detail.stops.length} scheduled visits · {detail.shape.length} shape points. Stops may include depots and other operational locations.</p>{!detail.shape.length&&<p>No shape supplied: only available stop locations are shown. No path is inferred.</p>}<h2>Stop inspector</h2>{chosen?<div className="inspector"><h3>{chosen.stop?.stop_name||'Unknown stop'}</h3><p>ID: {chosen.visit.stop_id}<br/>Sequence: {chosen.visit.stop_sequence}<br/>Scheduled arrival: {chosen.visit.arrival_time||'Not supplied'}<br/>Scheduled departure: {chosen.visit.departure_time||'Not supplied'}</p></div>:<p className="muted">Click a stop marker or a scheduled visit below.</p>}<h2>Planned stop sequence</h2><p className="muted">Service-day clock times as supplied, not observed arrivals. Times over 24:00 belong to the following calendar day.</p><ol className="stoplist">{detail.stops.map((v,i)=><li key={`${v.visit.stop_sequence}-${i}`}><button onClick={()=>setChosen(v)}>{v.visit.stop_sequence}. {v.stop?.stop_name||v.visit.stop_id}<small>{v.visit.arrival_time||'—'} → {v.visit.departure_time||'—'} · {v.visit.stop_id}{!v.stop?' · stop details missing':''}</small></button></li>)}</ol></>}
 </aside><main><div className="map" ref={node}/><div className="maplabel">OPERATION PLAN · REFERENCE ONLY<small>{detail?period(detail.package):'SELECT A PACKAGE, ROUTE AND TRIP'}</small></div>{tileError&&<div className="tilewarning">Background tiles unavailable; plan geometry still works.</div>}{!detail&&<div className="empty">{loading?'Loading…':'Select a planned trip to view its path and stops.'}</div>}</main></div>;
}
